genesys: use usleep instead of std::this_thread::sleep_for to re-enable thread less compile
Fixes:

  genesys/scanner_interface_usb.cpp: In member function ‘virtual void genesys::ScannerInterfaceUsb::sleep_us(unsigned int)’:
  genesys/scanner_interface_usb.cpp:484:10: error: ‘std::this_thread’ has not been declared
    484 |     std::this_thread::sleep_for(std::chrono::microseconds{microseconds});
        |          ^~~~~~~~~~~

Signed-off-by: Peter Seiderer <ps.report@gmx.net>